
export AFTERBURNER_NOASM=true
export DYNQ_AFTERBURNER_PLANS="${DYNQ_AFTERBURNER_PLANS:-false}"
export DYNQ_USE_AFTERBURNER_HARDCODED_QUERIES="${DYNQ_USE_AFTERBURNER_HARDCODED_QUERIES:-true}"
export DYNQ_AFTERBURNER_USE_SCHEMA="${DYNQ_AFTERBURNER_USE_SCHEMA:-false}"
export DYNQ_AFTERBURNER_USE_OPT_ACCESSOR="${DYNQ_AFTERBURNER_USE_OPT_ACCESSOR:-true}"
export DYNQ_GC_EACH_ITER="${DYNQ_GC_EACH_ITER:-true}"

export EXTRA_JAVA_OPTIONS+=" --experimental-options "
export EXTRA_JAVA_OPTIONS+=" --js.max-typed-array-length=2080374784 "
export EXTRA_JAVA_OPTIONS+=" --js.direct-byte-buffer=true "
export EXTRA_JAVA_OPTIONS+=" --max-old-space-size=8192 "
